#!/bin/bash
set -u -e;

# $1 — task id
# $2 — path to all shared data

id="${1}";
test -d "${2}";
readers="${2}/readers";
turnstile="${2}/turnstile";
data="${2}/data";

echo "${id} writer";

sem "${turnstile}" -x -- sem "${data}" -w;
sleep "0.$((RANDOM % 10))";
echo "${id} open" | tee -a "${data}";
sleep "0.$((RANDOM % 10))";
echo "${id} close" | tee -a "${data}";
sleep "0.$((RANDOM % 10))";
sem "${data}" -p;

sleep 1;
