#!/bin/bash
set -u;

function err { echo "$@" >&2; exit 1; }
function warn { echo "$@" >&2; }

echo "this=${1}, other=${2}";

echo "${1} busy";
sleep 2;
sleep "${RANDOM:0:1}";

echo "${1} ready, waiting for ${2}";
sem "${1}-done" -i0 -p;
sem "${2}-done" -i0 -w -u;

echo "${1} continues";
sleep 5;
