#!/bin/bash
set -u;

# ${1} — task id as assigned by demo
# ${2} — file that stores shared counter

sleep "${RANDOM:0:1}";

sem mutex -w;
v="$(($(< "${2}") + 1))";
echo "$v" > "${2}";
sem mutex -p;

echo "task ${1}: written ${v}";

