#!/bin/bash
set -u -e;

n="${1:-5}";
test "${n}" -gt 1 || n=5;

eating="$(mktemp)";

function cleanup {
    for i in $(seq "${1}"); do sem "fork-${i}" -u; done;
    sem footman -u;
    sem "${eating}" -u;
    rm "${eating}";
}

trap "cleanup '${n}'" EXIT;

for i in $(seq "${n}"); do sem "fork-${i}" -I1; done;
sem footman -I "$((n - 1))";
sem "${eating}" -I 1;

for i in $(seq "${n}"); do
    xterm -geometry 20x3 -e ./phil "${i}" "${n}" "${eating}"&
done;

while true; do
    #echo ---------------------------;
    #for i in $(seq "${n}"); do sem "fork-${i}" -q; done;
    cat "${eating}";
    sleep 1;
done;
