#!/bin/bash
set -u -e;

d="$(mktemp -d)";
readers="${d}/readers"
data="${d}/data";
turnstile="${d}/turnstile";

sem "${readers}" -I1;
sem "${data}" -I1;
sem "${turnstile}" -I1;

echo 0 > "${readers}";
cat >"${data}" <<EOF
nothing
written
EOF

for i in $(seq -w "${1:-10}"); do
    if test "$((RANDOM % 100))" -gt 50; then
        xterm -geometry 40x4 -e ./writer "${i}" "${d}"&
    else
        xterm -geometry 40x4 -e ./reader "${i}" "${d}"&
    fi;
done;


