#!/bin/bash
set -u -e;

id="${1}";
test -d "${2}";
readers="${2}/readers"
turnstile="${2}/turnstile";
data="${2}/data";

echo "${id} reader";

sem "${turnstile}" -x;
sem "${readers}" -w;
count="$(< ${readers})" 2>/dev/null;
test "${count}" = 0 && sem "${data}" -w;
echo "$((++count))" > "${readers}";
sem "${readers}" -p;

tail -2 "${data}";

sem "${readers}" -w;
count="$(< ${readers})" 2>/dev/null;
echo "$((--count))" > "${readers}";
test "${count}" = 0 && sem "${data}" -p;
sem "${readers}" -p;

sleep 5;
