#!/bin/bash
set -u -e -C;
shopt -s nullglob;

function err { echo "$@" >&2; exit 1; }
function warn { echo "$@" >&2; }

function ask_yN {
    local answer='';
    read -n 1 -s -p "$* [yN]" answer;
    if test "${answer}" = y; then
        echo yes;
        return 0;
    fi;
    echo no;
    return 1;
}

prefix='/dev/shm/sem.'; # see sem_overview(7)

pattern="*${1:-}${1:+*}";

list='';
for i in ${prefix}${pattern}; do
    s="/${i#${prefix}}";
    sem "${s}" -q
    stat -c "%10A %8U %8G" "${i}";
    ask_yN 'Remove?' && sem "${s}" -u;
done;
