#!/bin/bash
set -u -e -C;
shopt -s nullglob;

function err { echo "$@" >&2; exit 1; }
function warn { echo "$@" >&2; }

prefix='/dev/shm/sem.'; # see sem_overview(7)

pattern="${1:-*}";

found=false;
for i in ${prefix}${pattern}; do
    case "${i}" in
        "/${USER}:")
            echo "FIXME: decode %sequences!"
        *)
            echo "/${i#${prefix}}";;
    esac;
    found=true;
done;

${found} && exit 0;
exit 1;
