#!/bin/bash
set -u -e;

# $1 – phil's id
# $2 — total number
# $3 — shared number of eating phils

id="${1}";
n="${2}";
eating="${3}";
#TIX='/-\|';
#TIX=' .,oO0Oo,.';
TIX='>)|(<-';

while true; do
    echo "${id} thinks";
    sleep "$((1 + RANDOM % 5))";

    echo "${id} is hungry"; 
    sem footman -w;
    sem "fork-${id}" -w;
    sem "fork-$((id % n + 1))" -w;
    

    sem "${eating}" -w;
    echo "$(($(< "${eating}") + 1))" > "${eating}";
    sem "${eating}" -p;    

    echo -n "${id} eats          ";
    for i in $(seq "$((10 + RANDOM % 200))"); do
        echo -ne "\b\b${TIX:$((i % ${#TIX})):1} ";
        sleep 0.15;
    done;
    echo -e '\b\bdone';

    sem "${eating}" -w;
    echo "$(($(< "${eating}") - 1))" > "${eating}";
    sem "${eating}" -p;    


    sem "fork-${id}" -p;
    sem "fork-$((id % n + 1))" -p;
    sem footman -p;

done;
