#!/bin/bash
set -u -e;

# ${1} — task id as assigned by demo
# ${2} — file that stores shared counter

sem mutex -w;
test -r "${2}" && count="$(($(< "${2}") + 1))" || count=1;
echo "${count}" > "${2}";
sem mutex -p;

echo "task ${1} working";

sleep "${RANDOM:0:1}";

echo "task ${1} done";

sem mutex -w;
count="$(($(<"${2}") - 1))";
echo "${count}" > "${2}";
sem mutex -p;

test "${count}" -eq 0 && sem barrier -p;

sem barrier -x;

echo "task ${1} rendezvous";
sleep 1;
