#!/bin/bash
set -u -e;

function err { echo "$@" >&2; exit 1; }
function warn { echo "$@" >&2; }

if test -z "${2:-}"; then
    cat <<EOF
barrier ‹tmpfile› (-w|-i|-d|-u|-x ‹command› ...)
EOF
    exit;
fi;

counter="${1}"; shift;
barrier="barrier-${counter}";
mutex="barrier-${counter}-mutex";

case "${1}" in
    -w)
        sem "${barrier}" -i0 -x -u;
        rm -f "${counter}";
        sem "${mutex}" -u;
        ;;
    -i)
        sem "${mutex}" -i1 -w;
        count="$(($(< "${counter}" || echo 0) + 1))";
        echo "${count}" > "${counter}";
        sem "${mutex}" -p;
        ;;
    -d)
        sem "${mutex}" -i1 -w;
        count="$(($(< "${counter}" || echo 0) - 1))";
        echo "${count}" > "${counter}";
        sem "${mutex}" -p;
        test "${count}" -eq 0 && sem "${barrier}" -p;
        ;;
    -x)
        shift;
        "${0}" "${counter}" -i;
        eval "${@}";
        "${0}" "${counter}" -d;
        ;;
esac;
