#!/bin/bash
set -u -e;



total=20;

cat <<EOF
This demo needs the ‘barrier’ script from the ‘sem’ package installed.

I'll run 20 tasks with varying rnutime in parallel.  When all of them
have terminated, I'll terminate as well.
EOF

bar="$(barrier -n)";

for i in $(seq ${total}); do
    sleep "0.${RANDOM:0:1}";
    xterm -geometry 20x4 -e barrier "${bar}" -- ./task "${i}"&
done;

barrier "${bar}" -w;
echo "demo rendezvous";

barrier "${bar}" -u;
